apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    azure.com/repository-id: ${{ values.name | dump }}
    azure.com/organization: luishenrique92250483
    azure.com/project: backstage
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
